# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import course_detail_pb2 as course__detail__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in course_detail_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CourseDetailServiceStub(object):
    """--- 服务定义 ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCourseDetailMatch = channel.unary_unary(
                '/CourseDetailService/GetCourseDetailMatch',
                request_serializer=course__detail__pb2.GetCourseDetailMatchRequest.SerializeToString,
                response_deserializer=course__detail__pb2.GetCourseDetailMatchResponse.FromString,
                _registered_method=True)


class CourseDetailServiceServicer(object):
    """--- 服务定义 ---

    """

    def GetCourseDetailMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CourseDetailServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCourseDetailMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourseDetailMatch,
                    request_deserializer=course__detail__pb2.GetCourseDetailMatchRequest.FromString,
                    response_serializer=course__detail__pb2.GetCourseDetailMatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CourseDetailService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CourseDetailService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CourseDetailService(object):
    """--- 服务定义 ---

    """

    @staticmethod
    def GetCourseDetailMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CourseDetailService/GetCourseDetailMatch',
            course__detail__pb2.GetCourseDetailMatchRequest.SerializeToString,
            course__detail__pb2.GetCourseDetailMatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GetCourseDetailCommentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCourseCommentPage = channel.unary_unary(
                '/GetCourseDetailCommentService/GetCourseCommentPage',
                request_serializer=course__detail__pb2.GetCourseCommentPageRequest.SerializeToString,
                response_deserializer=course__detail__pb2.GetCourseCommentPageResponse.FromString,
                _registered_method=True)
        self.CreateCourseDetailCourseComment = channel.unary_unary(
                '/GetCourseDetailCommentService/CreateCourseDetailCourseComment',
                request_serializer=course__detail__pb2.CreateCourseDetailCourseCommentRequest.SerializeToString,
                response_deserializer=course__detail__pb2.CreateCourseDetailCourseCommentResponse.FromString,
                _registered_method=True)
        self.LikeCourseComment = channel.unary_unary(
                '/GetCourseDetailCommentService/LikeCourseComment',
                request_serializer=course__detail__pb2.LikeCourseCommentRequest.SerializeToString,
                response_deserializer=course__detail__pb2.LikeCourseCommentResponse.FromString,
                _registered_method=True)


class GetCourseDetailCommentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCourseCommentPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCourseDetailCourseComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LikeCourseComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetCourseDetailCommentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCourseCommentPage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourseCommentPage,
                    request_deserializer=course__detail__pb2.GetCourseCommentPageRequest.FromString,
                    response_serializer=course__detail__pb2.GetCourseCommentPageResponse.SerializeToString,
            ),
            'CreateCourseDetailCourseComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCourseDetailCourseComment,
                    request_deserializer=course__detail__pb2.CreateCourseDetailCourseCommentRequest.FromString,
                    response_serializer=course__detail__pb2.CreateCourseDetailCourseCommentResponse.SerializeToString,
            ),
            'LikeCourseComment': grpc.unary_unary_rpc_method_handler(
                    servicer.LikeCourseComment,
                    request_deserializer=course__detail__pb2.LikeCourseCommentRequest.FromString,
                    response_serializer=course__detail__pb2.LikeCourseCommentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GetCourseDetailCommentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GetCourseDetailCommentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GetCourseDetailCommentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCourseCommentPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GetCourseDetailCommentService/GetCourseCommentPage',
            course__detail__pb2.GetCourseCommentPageRequest.SerializeToString,
            course__detail__pb2.GetCourseCommentPageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCourseDetailCourseComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GetCourseDetailCommentService/CreateCourseDetailCourseComment',
            course__detail__pb2.CreateCourseDetailCourseCommentRequest.SerializeToString,
            course__detail__pb2.CreateCourseDetailCourseCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LikeCourseComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GetCourseDetailCommentService/LikeCourseComment',
            course__detail__pb2.LikeCourseCommentRequest.SerializeToString,
            course__detail__pb2.LikeCourseCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LoginServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoRefreshLogin = channel.unary_unary(
                '/LoginService/DoRefreshLogin',
                request_serializer=course__detail__pb2.RefreshLoginRequest.SerializeToString,
                response_deserializer=course__detail__pb2.RefreshLoginResponse.FromString,
                _registered_method=True)


class LoginServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoRefreshLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoRefreshLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.DoRefreshLogin,
                    request_deserializer=course__detail__pb2.RefreshLoginRequest.FromString,
                    response_serializer=course__detail__pb2.RefreshLoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LoginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LoginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoginService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoRefreshLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LoginService/DoRefreshLogin',
            course__detail__pb2.RefreshLoginRequest.SerializeToString,
            course__detail__pb2.RefreshLoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
