# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import course_id_pb2 as course__id__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in course_id_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CourseDetailServiceStub(object):
    """--- 服务定义 ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCourseDetailMatch = channel.unary_unary(
                '/CourseDetailService/GetCourseDetailMatch',
                request_serializer=course__id__pb2.GetCourseDetailMatchRequest.SerializeToString,
                response_deserializer=course__id__pb2.GetCourseDetailMatchResponse.FromString,
                _registered_method=True)


class CourseDetailServiceServicer(object):
    """--- 服务定义 ---
    """

    def GetCourseDetailMatch(self, request, context):
        """... 其他 RPC 方法可以根据需要添加
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CourseDetailServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCourseDetailMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourseDetailMatch,
                    request_deserializer=course__id__pb2.GetCourseDetailMatchRequest.FromString,
                    response_serializer=course__id__pb2.GetCourseDetailMatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CourseDetailService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CourseDetailService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CourseDetailService(object):
    """--- 服务定义 ---
    """

    @staticmethod
    def GetCourseDetailMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CourseDetailService/GetCourseDetailMatch',
            course__id__pb2.GetCourseDetailMatchRequest.SerializeToString,
            course__id__pb2.GetCourseDetailMatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
